version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devices_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devices_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - devices-network
    restart: always # Adicionando restart para garantir que a aplicação tente reconectar se houver problemas iniciais

  postgres:
    image: postgres:latest
    container_name: devices_postgres
    environment:
      POSTGRES_DB: devices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  devices-network:
    driver: bridge

volumes:
  postgres_data:
